apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myproject-ingress
  namespace: elephant-workshop  # Ensure namespace matches your services
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80, "HTTPS": 443}]'  # Listener on port 80
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/backend-protocol: HTTP  # Ensure the backend protocol is HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:976979239121:certificate/9f64a522-e6f2-4ace-9320-6c45a7d494ed
    alb.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: alb  # Ensure your Ingress class is set to 'alb'
  rules:
    - host: newbackend.Elephant-tank.com  # Ensure your domain is correctly mapped
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-backend-service  # Ensure the service name is correct
                port:
                  number: 8000  # Match the port exposed by the Django service
