apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: django-backend-hpa
  namespace: elephant-workshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: django-backend
  minReplicas: 3  # Minimum number of replicas
  maxReplicas: 10  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Target CPU utilization is 50%
